# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\Raf\\anaconda3\\envs\\ml-zoomcamp\\Lib\\site-packages\\numpy\\__init__.py'>

## Creating arrays


In [3]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [4]:
a[2]

3

In [5]:
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [8]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [10]:
n[0, 1]

2

In [11]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
n[2]

array([7, 8, 9])

In [13]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
n[:, 2] = [0, 1, 2]

In [15]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

## Randomly generated arrays


seed is used for making it actually random

In [16]:
np.random.rand(5,2)

array([[0.21031043, 0.43389145],
       [0.21077032, 0.11636119],
       [0.74938536, 0.90255455],
       [0.0333001 , 0.12499271],
       [0.16272425, 0.72209244]])

In [17]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [18]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [19]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
b = (10 + (a * 2)) ** 2 / 100

In [22]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [23]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [24]:
a

array([0, 1, 2, 3, 4])

In [25]:
a >= 2

array([False, False,  True,  True,  True])

In [26]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [27]:
a > b

array([False, False,  True,  True,  True])

In [28]:
a[a > b]

array([2, 3, 4])

^ all elements for which that is true

## Summarizing operations

In [29]:
a

array([0, 1, 2, 3, 4])

In [30]:
a.std()

1.4142135623730951

In [31]:
a.mean()

2.0

In [32]:
n.min()

0

### Next

Linear algebra refresher